### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by JanKruska** [MuhammadUsman05/Comparative-Process-Mining#1]
Hi,
I noticed that there was no license attached to your code. Since it is publicly available on GitHub I assume this is an oversight rather than intention.
If that is the case could you add a license to your code, since I would greatly assist me to be able to use parts of you code base as starting points.
If you need help in choosing a license take a look at https://choosealicense.com/

Regards
Jan

**Comment by madhubs08** [comment]
Added License Information
